blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://support.mfdlabs.com/
    about: Please ask and answer questions here.
  - name: Security
    url: https://security.mfdlabs.com/
    about: Please report security vulnerabilities here.
